// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI tool that analyzes project deadlines and provides stress reduction suggestions.
 *
 * - reduceStress - A function that handles the stress reduction process.
 * - ReduceStressInput - The input type for the reduceStress function.
 * - ReduceStressOutput - The return type for the reduceStress function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ReduceStressInputSchema = z.object({
  deadlines: z
    .array(
      z.object({
        taskName: z.string().describe('The name of the task.'),
        deadline: z.string().describe('The deadline of the task (ISO format).'),
        subjectWeightage: z.number().describe('The weightage of the subject (0-1).'),
        difficultyLevel: z.number().describe('The difficulty level of the subject (1-5).'),
      })
    )
    .describe('A list of tasks with deadlines, subject weightage, and difficulty level.'),
  batchLoad: z.number().describe('The overall workload of the batch (0-100).'),
});
export type ReduceStressInput = z.infer<typeof ReduceStressInputSchema>;

const ReduceStressOutputSchema = z.object({
  stressScore: z.number().describe('The calculated stress score based on deadlines and batch load.'),
  suggestions: z
    .array(
      z.object({
        taskName: z.string().describe('The name of the task.'),
        newDeadline: z.string().describe('The suggested new deadline for the task (ISO format).'),
        reason: z.string().describe('The reason for the suggested deadline change.'),
      })
    )
    .describe('A list of suggestions to reduce stress by adjusting deadlines.'),
});
export type ReduceStressOutput = z.infer<typeof ReduceStressOutputSchema>;

export async function reduceStress(input: ReduceStressInput): Promise<ReduceStressOutput> {
  return reduceStressFlow(input);
}

const prompt = ai.definePrompt({
  name: 'reduceStressPrompt',
  input: {schema: ReduceStressInputSchema},
  output: {schema: ReduceStressOutputSchema},
  prompt: `You are an AI assistant designed to help students reduce stress by analyzing their project deadlines and suggesting deadline adjustments.

  Calculate a stress score based on the proximity of deadlines, subject weightage, difficulty level, and overall batch load.
  Provide suggestions for adjusting deadlines to reduce stress, considering the overall batch load.

  Current Date: {{moment format="YYYY-MM-DD"}}

  Here are the tasks with deadlines, subject weightage, and difficulty levels:
  {{#each deadlines}}
  - Task: {{taskName}}, Deadline: {{deadline}}, Weightage: {{subjectWeightage}}, Difficulty: {{difficultyLevel}}
  {{/each}}

  Overall Batch Load: {{batchLoad}}

  Based on this information, calculate a stress score (higher is worse) and provide specific, actionable suggestions to reduce stress.  These suggestions should include the task name, a suggested new deadline (if applicable), and the reasoning behind the suggestion.
  The stress score should be based on how close the upcoming deadlines are, and the batch load (e.g. lots of high-difficulty tasks very soon = very high stress)
  Only suggest moving a deadline if it meaningfully reduces overall stress on the batch.
  Deadlines should be in ISO format.
  Ensure that all output fields are populated.
  Ensure that the date is in ISO format.
  `,
});

const reduceStressFlow = ai.defineFlow(
  {
    name: 'reduceStressFlow',
    inputSchema: ReduceStressInputSchema,
    outputSchema: ReduceStressOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
